---
title: "STAA 566 HW1"
author: "Ryan Miller"
output: html_document
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
## Clear workspace
rm( list = ls() )

## Req'd includes
library( ggplot2 )
library( scales  )
library( viridis )
```
```{r plots, fig.align = 'center'}
## Create plotting
x  <- seq( from = 0, to = 2 * pi, by = 0.01 )
y  <- c( sin( x )                    , cos( x ) )
fn <- c( rep( 'sin(x)', length( x ) ), rep( 'cos(x)', length( x ) ) )
d  <- data.frame( x, y, fn )

## Create custom scale for pi
pi_scales <- math_format( .x * pi, format = function(x) x / pi )

## Create plot
h_ <- ggplot( data = d, aes( x = x, y = y, color = fn ) ) +
    geom_line( lwd = 0.7 ) + theme_minimal() +
    scale_x_continuous( labels = pi_scales, breaks = c(0, pi/2, pi, 3*pi/2, 2*pi ) ) +
    scale_color_viridis( discrete = TRUE ) +
    theme( legend.title = element_blank() )

## Print the plot
h_
```
